CREATE TABLE "Users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(50) NOT NULL,
  "email" VARCHAR(50) NOT NULL,
  "password" VARCHAR(50) NOT NULL,
  "age" int
);

CREATE TABLE "Roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(50) NOT NULL
);

CREATE TABLE "User_Roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "role_id" int NOT NULL
);

CREATE TABLE "Courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" VARCHAR(50) NOT NULL,
  "description" VARCHAR(50) NOT NULL,
  "level" VARCHAR(50) NOT NULL,
  "teacher_id" int NOT NULL,
  "category_id" int NOT NULL
);

CREATE TABLE "Course_Videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" VARCHAR(50) NOT NULL,
  "url" VARCHAR(50) NOT NULL,
  "course_id" int NOT NULL
);

CREATE TABLE "Categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(50) NOT NULL
);

CREATE TABLE "Teachers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(50) NOT NULL
);

ALTER TABLE "User_Roles" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");

ALTER TABLE "User_Roles" ADD FOREIGN KEY ("role_id") REFERENCES "Roles" ("id");

ALTER TABLE "Courses" ADD FOREIGN KEY ("teacher_id") REFERENCES "Teachers" ("id");

ALTER TABLE "Courses" ADD FOREIGN KEY ("category_id") REFERENCES "Categories" ("id");

ALTER TABLE "Course_Videos" ADD FOREIGN KEY ("course_id") REFERENCES "Courses" ("id");
