CREATE TABLE "Users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" "VARCHAR(50, not null)",
  "email" "VARCHAR(50, not null)",
  "password" "VARCHAR(50, not null)",
  "age" int
);

CREATE TABLE "Roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" "VARCHAR(50, not null)"
);

CREATE TABLE "User_Roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "role_id" int
);

CREATE TABLE "Courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" "VARCHAR(50, not null)",
  "description" "VARCHAR(50, not null)",
  "level" "VARCHAR(50, not null)",
  "teacher_id" int,
  "category_id" int
);

CREATE TABLE "Course_Videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" "VARCHAR(50, not null)",
  "url" "VARCHAR(50, not null)",
  "course_id" int
);

CREATE TABLE "Categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" "VARCHAR(50, not null)"
);

CREATE TABLE "Teachers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" "VARCHAR(50, not null)"
);

ALTER TABLE "User_Roles" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");

ALTER TABLE "User_Roles" ADD FOREIGN KEY ("role_id") REFERENCES "Roles" ("id");

ALTER TABLE "Courses" ADD FOREIGN KEY ("teacher_id") REFERENCES "Teachers" ("id");

ALTER TABLE "Courses" ADD FOREIGN KEY ("category_id") REFERENCES "Categories" ("id");

ALTER TABLE "Course_Videos" ADD FOREIGN KEY ("course_id") REFERENCES "Courses" ("id");
